services:
  mongo:
    image: mongo
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.multistage
    ports:
      - '5000:5000'
      - '3001:3001'
    volumes:
      - /app/node_modules
      - ./:/app/
    depends_on:
      mongo:
        condition: service_healthy
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL="mongodb://mongo:27017/cloudbase"
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=hse
    depends_on:
      - mongo
    ports:
      - "8082:8081"
