export enum ServiceList {
  AUTHENTICATION = 'AUTHENTICATION',
  EMAIL = 'EMAIL',
  SERVERLESS = 'SERVERLESS',
  STATIC_SITE_HOSTING = 'STATIC_SITE_HOSTING',
  DEEP_LINK_GENERATION = 'DEEP_LINK_GENERATION',
  IMAGE_RESIZE = 'IMAGE_RESIZE',
}
